### ISSUE TITLE
Handle empty declarations with no line break between braces

### ISSUE THREAD

**Issue by natecook1000** [SwiftDocOrg/swiftdoc-parser#3]
As seen in Issue #2, using opening and closing braces on one line breaks the parser:

>     class NSFileHandle {}
>     struct String {}
>     // etc

leads to this error:

>     events.js:72
>          throw er; // Unhandled 'error' event
               ^
    Error: write EPIPE
         at errnoException (net.js:904:11)
         at Object.afterWrite (net.js:720:19)

**Comment by natecook1000** [comment]
@natecook1000, I've decided this is out of scope for swiftdoc-parser right now.
