### ISSUE TITLE
Support for Swift Package Manager supported project with C ModuleMaps

### ISSUE THREAD

**Issue by rfdickerson** [SwiftDocOrg/swiftdoc-parser#7]
I am having difficulty having my Swift Package Manager-based Linux Swift project work with the swiftdoc-parser. We use C Modulemaps for adding support for C libraries. When I use index.js for producing the documentation, I get the following error:

```
module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Release/pcre'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/rfdickerson/mil/swiftdoc-parser/node_modules/pcre/lib/pcre.js:1:74)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

At this point, does swiftdoc-parser work for Swift.org projects or just XCode?

**Comment by natecook1000** [comment]
Hi @rfdickerson, swiftdoc-parser has a very narrow focus: parsing the generated header for the Swift standard library. SPM support isn't on the radar. I've added some more information to the linked issue on the Kitura project. Thanks!
